---
docker_swarm_certs_dir: "/usr/local/var/{{ proj_name }}"
docker_swarm_cert_ca: "{{ docker_swarm_certs_dir }}/docker-swarm-ca.pem"
docker_swarm_cert_ca_key: "{{ docker_swarm_certs_dir }}/docker-swarm-ca-key.pem"
docker_swarm_cert_key: "{{ docker_swarm_certs_dir }}/docker-swarm-key.pem"
docker_swarm_cert: "{{ docker_swarm_certs_dir }}/docker-swarm.pem"
docker_swarm_binding_addr: 0.0.0.0
docker_options: >-
  --tlsverify
  --tlscacert={{ docker_swarm_cert_ca }}
  --tlscert={{ docker_swarm_cert }}
  --tlskey={{ docker_swarm_cert_key }}
  -H tcp://{{ docker_swarm_binding_addr }}
  -H unix:///var/run/docker.sock
  --bip={{ docker_daemon_network }}
  --graph={{ docker_daemon_graph }}

core_stack_path: "/usr/local/var/{{ proj_name }}/core-stack.yml"
