# -*- mode: ruby -*-
# vi: set ft=ruby :

PROJECT_NAME = "aeris"
PUBLIC_NETWORK_IF = "en0: Wi-Fi (AirPort)"
VM_INSTANCES = 2
VM_MEMORY = "1024"
VM_CPUS = 1

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = VM_MEMORY
    vb.cpus = VM_CPUS
  end

  all_instance_names = (1..VM_INSTANCES).map { |i| "kaisa-linux-#{i}" }

  # Multi instance
  (1..VM_INSTANCES).each do |i|
    instance_name = "#{PROJECT_NAME}-linux-#{i}"
    config.vm.define instance_name do |instance|
      instance.vm.box = "centos/7"
      instance.vm.hostname = instance_name
      instance.vm.network "public_network", bridge: PUBLIC_NETWORK_IF
      instance.vm.provision "ansible" do |ansible|
        ansible.playbook = "../ansible/docker-swarm.yml"
        ansible.config_file = "../ansible/ansible.cfg"
        ansible.tags = "dummy"
        ansible.become = true
        ansible.groups = {
          "docker_engine" => all_instance_names,
          "docker_swarm_manager" => all_instance_names,
          "all:vars" => {
            "docker_swarm_interface" => "eth1",
            "ansible_ssh_common_args" => "-o StrictHostKeyChecking=no"
          }
        }
      end
    end
  end

end

