version: '3.7'
services:

  portainer:
    image: portainer/portainer
    command:
      - -H
      - tcp://tasks.portainer_agent:9001
      - --tlsskipverify
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - web
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
        - traefik.frontend.rule=Host:portainer.kaisa.skivent.co,portainer.localhost
        - traefik.port=9000

  portainer_agent:
    image: portainer/agent
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer_agent
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  traefik:
    image: traefik:v1.7.4
    command:
      - --api
      - --docker
      - --docker.domain=docker.localhost
      - --docker.swarmmode=true
      - --docker.watch=true
      - --docker.network=web
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https Compress:true"
      - "--entrypoints=Name:https Address::443 TLS:/run/secrets/traefik-cert,/run/secrets/traefik-cert-key"
      - --defaultentrypoints=http,https
      - --loglevel=INFO
    secrets:
      - traefik-cert
      - traefik-cert-key
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:traefik.kaisa.skivent.co,traefik.localhost
        - traefik.port=8080

  registry:
    image: registry:2
    ports:
      - 5000:5000
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:registry.kaisa.skivent.co,registry.localhost
        - traefik.port=5000

volumes:
  portainer:
  registry:

secrets:
  traefik-cert:
    external: true
  traefik-cert-key:
    external: true

networks:
  web:
    external: true
